In [6]:
import numpy as np 

In [16]:
np1 = np.array([1,2,3,'s1','s2',2+2,3*2,{'name':'arc'}])

In [17]:
np1

array([1, 2, 3, 's1', 's2', 4, 6, {'name': 'arc'}], dtype=object)

In [19]:
type(np1)

numpy.ndarray

In [22]:
np2 = list(range(1,50,2))

In [24]:
print(np2)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [26]:
print(np.min(np2))

1


In [34]:
l1 =list(range(5,51,5)) 

In [35]:
l1

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [36]:
np.min(l1)

5

In [41]:
np3 = np.array([[0,1,2],[3,4,5]])

In [45]:
np3

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
print(l1)
print()
print(np1)
print()
print(np3)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

[1 2 3 's1' 's2' 4 6 {'name': 'arc'}]

[[0 1 2]
 [3 4 5]]


In [53]:
print(f'np1.shape()={np1.shape}')

print(f'np3.shape()={np3.shape}')

print(f'l1.shape={len(l1)}')

np1.shape()=(8,)
np3.shape()=(2, 3)
l1.shape=10


In [55]:
print(f'type(np1)= {type(np1)} , dtype(np1)={np1.dtype}')

type(np1)= <class 'numpy.ndarray'> , dtype(np1)=object


In [60]:
print(f'type(np3)= {type(np3)} , dtype(np3)={np3.dtype}')

type(np3)= <class 'numpy.ndarray'> , dtype(np3)=int32


In [62]:
np3

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
l2 = [[0, 1, 2],
       [3, 4, 5]]

In [82]:
l2[0][1] = 3

In [83]:
np3

array([[0, 3, 2],
       [3, 4, 5]])

In [84]:
np3[0,1] = 3

In [85]:
np3

array([[0, 3, 2],
       [3, 4, 5]])

In [87]:
l2

[[0, 3, 2], [3, 4, 5]]

In [90]:
l2[0][1] = 'text'
l2

[[0, 'text', 2], [3, 4, 5]]

In [95]:
mat1 = np.arange(10,100,5)

print(f'matRange = {mat1}')
print()
npRange = np.array(range(10,100,5))

print(f'npRange = {npRange}')

matRange = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]

npRange = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [101]:
mat1 = np.linspace(0,10,20)

print(f'mat1 = {mat1}')
print()
print(f'mat1_length = {mat1.shape}')

mat1 = [ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]

mat1_length = (20,)


In [102]:
mat2 = np.random.rand(5,5)
mat2

array([[0.29307625, 0.06870284, 0.60167294, 0.89073915, 0.91861736],
       [0.81917601, 0.18694732, 0.86261528, 0.95662007, 0.38266847],
       [0.07900497, 0.2360157 , 0.05746692, 0.73735867, 0.44728988],
       [0.08865575, 0.76856521, 0.35209744, 0.06461452, 0.68395876],
       [0.87349098, 0.24461701, 0.48140924, 0.63864537, 0.85915184]])